export const TASK_REPOSITORY = 'TASK_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const PROFILE_REPOSITORY = 'PROFILE_REPOSITORY';
export const POST_REPOSITORY = 'POST_REPOSITORY';
export const DATA_SOURCE = 'DATA_SOURCE';
